"""Initial migration after reset

Revision ID: 06516267ad45
Revises:
Create Date: 2025-11-09 21:37:24.785414

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06516267ad45"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("change_note", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dataset_version", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dataset_version_dataset_id"), ["dataset_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_version_dataset_id"))

    op.drop_table("dataset_version")
    # ### end Alembic commands ###
