"""Añade modelos TabularMetaData, Column y Metrics

Revision ID: ddba84b9a16a
Revises: 2460_polymorphic_single_table
Create Date: 2025-11-03 19:15:15.388577

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ddba84b9a16a"
down_revision = "2460_polymorphic_single_table"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tabular_meta_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hubfile_id", sa.Integer(), nullable=True),
        sa.Column("delimiter", sa.String(length=5), nullable=True),
        sa.Column("encoding", sa.String(length=20), nullable=True),
        sa.Column("has_header", sa.Boolean(), nullable=True),
        sa.Column("n_rows", sa.Integer(), nullable=True),
        sa.Column("n_cols", sa.Integer(), nullable=True),
        sa.Column("primary_keys", sa.JSON(), nullable=True),
        sa.Column("index_cols", sa.JSON(), nullable=True),
        sa.Column("sample_rows", sa.JSON(), nullable=True),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id"),
    )
    op.create_table(
        "tabular_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("null_ratio", sa.Float(), nullable=True),
        sa.Column("avg_cardinality", sa.Float(), nullable=True),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id"),
    )
    op.create_table(
        "tabular_column",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("dtype", sa.String(length=50), nullable=True),
        sa.Column("null_count", sa.Integer(), nullable=True),
        sa.Column("unique_count", sa.Integer(), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("meta_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meta_id"],
            ["tabular_meta_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tabular_column")
    op.drop_table("tabular_metrics")
    op.drop_table("tabular_meta_data")
    # ### end Alembic commands ###
